server:
  port: 5004
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/EduardoErenasL/micro-service
          search-paths: config-data
  application:
    name: config-service
